#!/usr/bin/env bash
bind 'set completion-ignore-case on'

bleopt history_share=1

bleopt indent_offset=2
bleopt indent_tabs=0

ble-sabbrev L='| less'
ble-sabbrev B='| bat'
ble-sabbrev G='| grep'
ble-sabbrev R='| rg'

ble-face disabled='fg=1'
ble-face auto_complete='fg=white,bg=69'
ble-face command_alias='fg=white'

ble-import -d contrib/fzf-completion
ble-import -d contrib/fzf-key-bindings

# Key bindings can be controlled with the shell function, ble-bind. For example, with the following setting, "Hello, world!" will be inserted on typing C-x h

# Use tab <C-i> to auto-complete
ble-bind -m 'auto_complete' -f 'C-i' 'auto_complete/insert-on-end'

# Ctrl-c to kill line and start insert mode
ble-bind -m vi_nmap -f 'C-c' 'discard-line vi_imap/overwrite-mode'

