#!/usr/bin/env bash
#
# Usage: ./my-script arg1 [arg2]
#
cd "${0%/*}"
source utilities.bash

# download
wget -O /tmp/fd.tar.gz https://github.com/sharkdp/fd/releases/download/v8.3.0/fd-v8.3.0-x86_64-unknown-linux-musl.tar.gz

# extract
cd /tmp
rm -r fd
mkdir fd
tar xf fd.tar.gz

# install
FD="${0%/*}/../bin/fd"
cp /tmp/fd-*/fd "$FD"
chmod u+x "$FD"
success_msg 'fd hopefully installed' && exit 0
