#!/usr/bin/env bash
# https://github.com/dvorka/hstr
set -ex

cd /tmp
[ -d /tmp/hstr ] && rm -rf /tmp/hstr
git clone https://github.com/dvorka/hstr.git

# dependencies: automake, libncursesw5-dev, lib32readline-dev
cd hstr/build/tarball
./tarball-automake.sh

cd ../..
./configure && make && sudo make install
