#!/usr/bin/env bash
#
# Usage: ./install-nvim-appimage
#
# releases: https://github.com/neovim/neovim/releases/tag/nightly
cd "${0%/*}/.."
NVIM="$PWD/squashfs-root/usr/bin/nvim"
[[ -x "$NVIM" ]] && exit 0

set -ex

URL='https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage'
FILE="$PWD/bin/${URL##*/}"

wget -nc -P "$PWD/bin/" "$URL"
chmod u+x "$FILE"

"$FILE" --appimage-extract
ln -sf "$NVIM" "$PWD/bin/nvim"
