#!/usr/bin/env bash
# releases: https://github.com/tmux/tmux/releases
set -ex
cd "${0%/*}/.."

URL='https://github.com/tmux/tmux/releases/download/3.1b/tmux-3.1b-x86_64.AppImage'
FILE="$PWD/bin/${URL##*/}"

wget -nc -P "$PWD/bin/" "$URL"
chmod u+x "$FILE"

"$FILE" --appimage-extract
ln -sf "$PWD/squashfs-root/usr/bin/tmux" "$PWD/bin/tmux"
