#!/usr/bin/env bash
# releases: https://github.com/tmux/tmux/releases
cd "${0%/*}/.."
TMUX="$PWD/squashfs-root/usr/bin/tmux"
[[ -x "$TMUX" ]] && exit 0

set -ex

URL='https://github.com/tmux/tmux/releases/download/3.1b/tmux-3.1b-x86_64.AppImage'
FILE="$PWD/bin/${URL##*/}"

wget -nc -P "$PWD/bin/" "$URL"
chmod u+x "$FILE"

"$FILE" --appimage-extract
ln -sf "$TMUX" "$PWD/bin/tmux"
