#!/usr/bin/env bash
set -ex

cd /tmp
wget -O lazygit.tar.gz 'https://github.com/jesseduffield/lazygit/releases/download/v0.31.4/lazygit_0.31.4_Linux_x86_64.tar.gz'
tar xvf lazygit.tar.gz

mkdir -p ~/portable-config/bin
cp lazygit ~/portable-config/bin/lazygit
