#!/usr/bin/env bash
#
# Usage: ./my-script arg1 [arg2]
#
cd "${0%/*}"
source utilities.bash
#takes_at_least_n_args 1 && exit 1
#success_msg 'Script executed' && exit

cd /tmp
git clone git@github.com:eradman/entr.git

cd entr
./configure
make

ENTR="${0%/*}/../bin/entr"
mv entr "$ENTR"
chmod u+x "$ENTR"
success_msg 'entr hopefully installed' && exit 0

