#!/usr/bin/env bash
#
# Usage: ./install-fzf
#
cd "${0%/*}/.."
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --bin

wget -qO- https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux > ./bin/fzf-tmux
chmod u+x ./bin/fzf-tmux

wget -qO- https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.bash > ./bashrc.d/fzf-completions.bashrc
wget -qO- https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash > ./bashrc.d/fzf-keybindings.bashrc
