#!/usr/bin/env bash
set -ex
wget -q https://github.com/akinomyoga/ble.sh/releases/download/v0.4.0-devel2/ble-0.4.0-devel2.tar.xz
tar xJf ble-0.4.0-devel2.tar.xz -C ~/.local/share/blesh
chmod u+x ~/.local/share/blesh/ble.sh
