#!/usr/bin/env bash
# https://github.com/dvorka/hstr
set -ex

cd /tmp
git clone https://github.com/dvorka/hstr.git

cd hstr/build/tarball
./tarball-automake.sh

cd ../..
./configure && make && make install
