#!/usr/bin/env bash
#
# Usage: ./install-forgit
# Website: https://github.com/wfxr/forgit
# Keybindings:
#   ga	FORGIT_ADD_FZF_OPTS
#   glo	FORGIT_LOG_FZF_OPTS
#   gi	FORGIT_IGNORE_FZF_OPTS
#   gd	FORGIT_DIFF_FZF_OPTS
#   grh	FORGIT_RESET_HEAD_FZF_OPTS
#   gcf	FORGIT_CHECKOUT_FILE_FZF_OPTS
#   gcb	FORGIT_CHECKOUT_BRANCH_FZF_OPTS
#   gco	FORGIT_CHECKOUT_COMMIT_FZF_OPTS
#   gss	FORGIT_STASH_FZF_OPTS
#   gclean	FORGIT_CLEAN_FZF_OPTS
#   grb	FORGIT_REBASE_FZF_OPTS
#   gfu	FORGIT_FIXUP_FZF_OPTS
cd "${0%/*}/../bashrc.d"
wget -O forgit.sh git.io/forgit
chmod u+x forgit.sh
