#!/usr/bin/env bash
cd /tmp

[ -d ble.sh ] && rm -rf ble.sh
git clone --recursive https://github.com/akinomyoga/ble.sh.git
make -C ble.sh install PREFIX=~/.local

chmod u+x ~/.local/share/blesh/ble.sh
