#!/usr/bin/env bash
export HERE="$(dirname "$(readlink -f "$0")")/.."
export TERM='xterm'

"$HERE/scripts/install-tmux-appimage"
"$HERE/scripts/install-nvim-appimage"

mkdir -p ~/.local/share/bin
ln -sf "$HERE/scripts/run-me.bash" '~/.local/share/bin/michael' 2> /dev/null

TMUXRC="$HERE/config/tmux.conf"
CONFIG='portable-config'

exec "$HERE/bin/tmux" -f "$TMUXRC" -L "$CONFIG" \
	new-session -A -s ${@:-default} \; \
	choose-tree -s
